# Résultats des Tests API

## Test du 2025-02-26 22:53:24

### POST /auth/login
Status: None
Succès: ❌

#### Détails de la Requête
```json
{
  "url": "http://localhost:8000/auth/login",
  "method": "POST",
  "headers": null,
  "data": {
    "username": "admin",
    "password": "prodPassword"
  },
  "files": null
}
```

#### Réponse
```json
null
```

#### Erreur
```
HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc537755630>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

---

### POST /predict
Status: None
Succès: ❌

#### Détails de la Requête
```json
{
  "url": "http://localhost:8000/predict",
  "method": "POST",
  "headers": {
    "Authorization": "Bearer None"
  },
  "data": {
    "image_path": "/app/api-test-endpoint/images-test.jpg"
  },
  "files": null
}
```

#### Réponse
```json
null
```

#### Erreur
```
HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc537755f60>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

---

### POST /predict_batch
Status: None
Succès: ❌

#### Détails de la Requête
```json
{
  "url": "http://localhost:8000/predict_batch",
  "method": "POST",
  "headers": {
    "Authorization": "Bearer None"
  },
  "data": {
    "images": [
      "/app/api-test-endpoint/multi-image-test.jpg",
      "/app/api-test-endpoint/multi-image-test-2.jpg"
    ]
  },
  "files": [
    {
      "filename": "/app/api-test-endpoint/multi-image-test.jpg"
    },
    {
      "filename": "/app/api-test-endpoint/multi-image-test-2.jpg"
    }
  ]
}
```

#### Réponse
```json
null
```

#### Erreur
```
HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /predict_batch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc537756800>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

---

### POST /predict_zip
Status: None
Succès: ❌

#### Détails de la Requête
```json
{
  "url": "http://localhost:8000/predict_zip",
  "method": "POST",
  "headers": {
    "Authorization": "Bearer None"
  },
  "data": {
    "zip_file": "/app/api-test-endpoint/zip-test.zip"
  },
  "files": {
    "filename": "/app/api-test-endpoint/zip-test.zip"
  }
}
```

#### Réponse
```json
null
```

#### Erreur
```
HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /predict_zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc53770a6b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

---

